<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TemporaLinq\TemporaLinq.csproj" />
      <ProjectReference Include="..\TemporaLinq.Astronomy\TemporaLinq.Astronomy.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Memoizer.NETStandard" Version="2023.5.1.16" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="NorthAmerica\" />
    </ItemGroup>

</Project>
